# Generated by Django 5.1 on 2024-10-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_productmanufacturer_product_part_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_long',
            field=models.TextField(null=True),
        ),
    ]
