# Generated by Django 5.1 on 2024-10-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_product_description_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lead_time_weeks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='markup_adjust',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='obsolete',
            field=models.BooleanField(default=False, verbose_name='obsolete'),
        ),
        migrations.AddField(
            model_name='product',
            name='replaced',
            field=models.BooleanField(default=False, verbose_name='replaced'),
        ),
        migrations.AddField(
            model_name='product',
            name='replaced_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unique_identifier',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
